import type {
  ArcWithTranslation,
  CoordinatorMessageSummary,
  Language,
  SceneWithContent,
  WitnessVideo,
} from './types';

export const mockLanguages: Language[] = [
  { id: 'lang-en', code: 'en', name: 'English', native_name: 'English', is_active: true },
  { id: 'lang-zh', code: 'zh', name: 'Chinese', native_name: '中文', is_active: true },
  { id: 'lang-es', code: 'es', name: 'Spanish', native_name: 'Español', is_active: true },
  { id: 'lang-hi', code: 'hi', name: 'Hindi', native_name: 'हिन्दी', is_active: true },
  { id: 'lang-ko', code: 'ko', name: 'Korean', native_name: '한국어', is_active: true },
  { id: 'lang-ar', code: 'ar', name: 'Arabic', native_name: 'العربية', is_active: true },
];

export const mockArcs: ArcWithTranslation[] = [
  {
    id: 'arc-grief',
    slug: 'when-he-wept',
    order: 1,
    is_published: true,
    emotional_key: 'grief',
    title: 'When He Wept',
    tagline: 'A story for the ache that stays after the room goes quiet.',
  },
  {
    id: 'arc-doubt',
    slug: 'the-night-he-answered',
    order: 2,
    is_published: true,
    emotional_key: 'doubt',
    title: 'The Night He Answered',
    tagline: 'A story for the person who needs more than slogans.',
  },
  {
    id: 'arc-searching',
    slug: 'the-king-who-came',
    order: 3,
    is_published: true,
    emotional_key: 'searching',
    title: 'The King Who Came',
    tagline: 'A story about a rescue no one expected.',
  },
  {
    id: 'arc-curiosity',
    slug: 'come-and-see',
    order: 4,
    is_published: true,
    emotional_key: 'curiosity',
    title: 'Come and See',
    tagline: 'A story for the person who is open, observant, and not yet convinced.',
  },
  {
    id: 'arc-anger',
    slug: 'the-storm-he-stilled',
    order: 5,
    is_published: true,
    emotional_key: 'anger',
    title: 'The Storm He Stilled',
    tagline: 'A story for the noise inside you when everything feels too much.',
  },
];

export const mockArc = mockArcs.find((arc) => arc.slug === 'the-king-who-came') ?? mockArcs[0];

export const mockCoordinatorMessages: CoordinatorMessageSummary[] = [
  {
    id: 'msg-1',
    reply_token: 'mock-reply-token',
    lang: 'en',
    emotional_key: 'searching',
    message:
      'I thought this would feel distant, but the invitation scene felt like someone was speaking directly into my questions.',
    coordinator_reply: null,
    created_at: '2026-03-27T18:15:00.000Z',
    arc_slug: 'the-king-who-came',
    arc_title: 'The King Who Came',
    sender_name: 'Priya',
    path_summary: 'Searching path • The Waiting → The Invitation',
  },
  {
    id: 'msg-2',
    reply_token: 'mock-doubt-reply-token',
    lang: 'en',
    emotional_key: 'doubt',
    message:
      'The locked room scene felt honest. I am not ready to say I believe, but I do want to keep asking the real questions.',
    coordinator_reply:
      'Thank you for saying that plainly. You do not need to rush past your questions here. If you want, I can send one more story that meets doubt with the same patience.',
    created_at: '2026-03-27T16:40:00.000Z',
    arc_slug: 'the-night-he-answered',
    arc_title: 'The Night He Answered',
    sender_name: 'Kwame',
    path_summary: 'Doubt path • The Locked Room → My Lord, My God',
  },
  {
    id: 'msg-3',
    reply_token: 'mock-grief-reply-token',
    lang: 'ko',
    emotional_key: 'grief',
    message:
      'I do not have words for all of this yet. I just needed somewhere that did not rush me past the ache.',
    coordinator_reply: null,
    created_at: '2026-03-26T21:05:00.000Z',
    arc_slug: 'when-he-wept',
    arc_title: 'When He Wept',
    sender_name: 'Hannah',
    path_summary: 'Grief path • The Empty Room → At the Tomb',
  },
];

export const mockConnectMessage = {
  id: mockCoordinatorMessages[0].id,
  reply_token: mockCoordinatorMessages[0].reply_token,
};

const mockScenesList: SceneWithContent[] = [
  {
    id: 'scene-grief-1',
    arc_id: 'arc-grief',
    slug: 'the-empty-room',
    is_start: true,
    is_end: false,
    light_world: false,
    title: 'The Empty Room',
    body: 'The room still holds their shape. The chair. The cup. The quiet. Grief is strange that way. The world keeps moving while one part of it feels as though it stopped.\n\nMary and Martha knew that feeling. By the time Jesus reached them, the house had already learned how to whisper around sorrow.',
    audio_url: null,
    choices: [
      {
        id: 'choice-grief-1',
        scene_id: 'scene-grief-1',
        next_scene_id: 'scene-grief-2',
        order: 0,
        label: 'Walk with him toward the house of grief',
      },
    ],
  },
  {
    id: 'scene-grief-2',
    arc_id: 'arc-grief',
    slug: 'the-road-to-bethany',
    is_start: false,
    is_end: false,
    light_world: false,
    title: 'The Road to Bethany',
    body: 'When Martha met him on the road, she did not speak carefully. She spoke honestly. "If you had been here, my brother would not have died."\n\nJesus did not recoil from the accusation. He stayed close enough to hear the heartbreak underneath it.',
    audio_url: null,
    choices: [
      {
        id: 'choice-grief-2',
        scene_id: 'scene-grief-2',
        next_scene_id: 'scene-grief-2b',
        order: 0,
        label: 'Keep going to the place where he wept',
      },
    ],
  },
  {
    id: 'scene-grief-2b',
    arc_id: 'arc-grief',
    slug: 'the-stone-still-sealed',
    is_start: false,
    is_end: false,
    light_world: false,
    title: 'The Stone Still Sealed',
    body: 'When they reached the tomb, the stone was still in place. Nothing looked resolved. Nothing looked ready to change.\n\nSometimes grief is hardest at that exact edge: when the loss is already real and the future still looks shut.',
    audio_url: null,
    choices: [
      {
        id: 'choice-grief-2b',
        scene_id: 'scene-grief-2b',
        next_scene_id: 'scene-grief-2c',
        order: 0,
        label: 'Stay with him at the edge of what feels sealed',
      },
    ],
  },
  {
    id: 'scene-grief-2c',
    arc_id: 'arc-grief',
    slug: 'the-sisters-still-standing',
    is_start: false,
    is_end: false,
    light_world: false,
    title: 'The Sisters Still Standing',
    body: 'Before anything changed, the sisters were still standing in front of a sealed grave with all their questions intact. Jesus did not ask them to skip that moment.\n\nHe stayed with them in the place where sorrow had not yet turned into relief.',
    audio_url: null,
    choices: [
      {
        id: 'choice-grief-2c',
        scene_id: 'scene-grief-2c',
        next_scene_id: 'scene-grief-3',
        order: 0,
        label: 'Stay long enough to see what love does at the tomb',
      },
    ],
  },
  {
    id: 'scene-grief-3',
    arc_id: 'arc-grief',
    slug: 'at-the-tomb',
    is_start: false,
    is_end: true,
    light_world: true,
    title: 'At the Tomb',
    body: 'At the tomb, Jesus did not hurry past their grief to a lesson. He wept. Before he changed anything, he entered the sorrow that was already there.\n\nThe God who could raise the dead first stood beside the mourners and cried.',
    audio_url: null,
    choices: [],
  },
  {
    id: 'scene-doubt-1',
    arc_id: 'arc-doubt',
    slug: 'the-locked-room',
    is_start: true,
    is_end: false,
    light_world: false,
    title: 'The Locked Room',
    body: 'The room was closed. The doors were shut. Everyone inside had already learned how hope can embarrass you.\n\nThomas was not there for the first story. He only had the secondhand version: "We saw him." Sometimes doubt begins exactly there, at the point where someone else says they know.',
    audio_url: null,
    choices: [
      {
        id: 'choice-doubt-1',
        scene_id: 'scene-doubt-1',
        next_scene_id: 'scene-doubt-2',
        order: 0,
        label: 'Stay with Thomas in the unanswered night',
      },
    ],
  },
  {
    id: 'scene-doubt-2',
    arc_id: 'arc-doubt',
    slug: 'the-offered-hands',
    is_start: false,
    is_end: false,
    light_world: false,
    title: 'The Offered Hands',
    body: 'A week later Jesus came back into the locked room and spoke directly to the doubter. Not around him. Not over him. To him.\n\n"Put your finger here. See my hands." He met skepticism with nearness, not shame.',
    audio_url: null,
    choices: [
      {
        id: 'choice-doubt-2',
        scene_id: 'scene-doubt-2',
        next_scene_id: 'scene-doubt-2b',
        order: 0,
        label: 'Hear what happens when doubt is answered',
      },
    ],
  },
  {
    id: 'scene-doubt-2b',
    arc_id: 'arc-doubt',
    slug: 'the-week-between',
    is_start: false,
    is_end: false,
    light_world: false,
    title: 'The Week Between',
    body: 'Thomas lived for a week between rumor and encounter. He was not cynical because he asked for something solid. He was simply not willing to build his life on borrowed certainty.\n\nJesus did not hurry that week along. He met him in it.',
    audio_url: null,
    choices: [
      {
        id: 'choice-doubt-2b',
        scene_id: 'scene-doubt-2b',
        next_scene_id: 'scene-doubt-2c',
        order: 0,
        label: 'See what happens when Jesus comes back for the doubter',
      },
    ],
  },
  {
    id: 'scene-doubt-2c',
    arc_id: 'arc-doubt',
    slug: 'the-room-before-daybreak',
    is_start: false,
    is_end: false,
    light_world: false,
    title: 'The Room Before Daybreak',
    body: 'The room held that strange silence that comes after too many broken expectations. No one could argue Thomas into peace from there.\n\nHe needed more than reassurance. He needed Jesus to come all the way into the room where his doubt still lived.',
    audio_url: null,
    choices: [
      {
        id: 'choice-doubt-2c',
        scene_id: 'scene-doubt-2c',
        next_scene_id: 'scene-doubt-3',
        order: 0,
        label: 'Stay until the answer stands in front of him',
      },
    ],
  },
  {
    id: 'scene-doubt-3',
    arc_id: 'arc-doubt',
    slug: 'my-lord-my-god',
    is_start: false,
    is_end: true,
    light_world: true,
    title: 'My Lord, My God',
    body: 'Thomas did not stop being thoughtful when he believed. He simply found a truth sturdy enough to bear his whole weight.\n\nJesus did not ask him to pretend certainty. He gave him something real enough to touch.',
    audio_url: null,
    choices: [],
  },
  {
    id: 'scene-searching-1',
    arc_id: 'arc-searching',
    slug: 'the-waiting',
    is_start: true,
    is_end: false,
    light_world: false,
    title: 'The Waiting',
    body: 'Long before your own restless questions had words, the world already knew the ache of waiting. Things were beautiful, and broken, and no one seemed able to mend them from the inside.\n\nStill, a whisper kept passing from generation to generation: someone is coming. Someone will make the shattered world hold together again. And the world waited with that rumor in its mouth.',
    audio_url: null,
    choices: [
      {
        id: 'choice-searching-1',
        scene_id: 'scene-searching-1',
        next_scene_id: 'scene-searching-2',
        order: 0,
        label: 'Keep listening for the King who was coming',
      },
    ],
  },
  {
    id: 'scene-searching-2',
    arc_id: 'arc-searching',
    slug: 'a-different-kind-of-king',
    is_start: false,
    is_end: false,
    light_world: false,
    title: 'A Different Kind of King',
    body: 'When the King finally came, he did not arrive with banners, horses, or a palace gate opening before him. He came small enough to be held, in a place borrowed from animals and night.\n\nThe one who hung the stars above the earth chose, for a while, to sleep beneath them.',
    audio_url: null,
    choices: [
      {
        id: 'choice-searching-2a',
        scene_id: 'scene-searching-2',
        next_scene_id: 'scene-searching-3',
        order: 0,
        label: 'Follow the shepherds who heard the news first',
      },
      {
        id: 'choice-searching-2b',
        scene_id: 'scene-searching-2',
        next_scene_id: 'scene-searching-4',
        order: 1,
        label: 'Follow the scholars who crossed far countries to find him',
      },
    ],
  },
  {
    id: 'scene-searching-3',
    arc_id: 'arc-searching',
    slug: 'the-shepherds-path',
    is_start: false,
    is_end: false,
    light_world: false,
    title: "The Shepherds' Path",
    body: 'Out on the dark hills, where no one important was watching, shepherds heard the night split with news too large for ordinary voices. A Savior had been born.\n\nThey did not debate it for long. They ran toward the place where wonder had touched the earth.',
    audio_url: null,
    choices: [
      {
        id: 'choice-searching-3',
        scene_id: 'scene-searching-3',
        next_scene_id: 'scene-searching-3b',
        order: 0,
        label: 'Run with them toward what they found',
      },
    ],
  },
  {
    id: 'scene-searching-3b',
    arc_id: 'arc-searching',
    slug: 'the-sky-went-singing',
    is_start: false,
    is_end: false,
    light_world: false,
    title: 'The Sky Went Singing',
    body: 'The night refused to remain a plain black ceiling. Light broke through it. Voices poured through it. The shepherds realized, almost all at once, that heaven was not only speaking. Heaven was singing.\n\nAnd somehow the song had found them first. Before they could explain it, they knew this much: joy had come near enough to hear.',
    audio_url: null,
    choices: [
      {
        id: 'choice-searching-3b',
        scene_id: 'scene-searching-3b',
        next_scene_id: 'scene-searching-5',
        order: 0,
        label: 'Keep following the song they ran toward',
      },
    ],
  },
  {
    id: 'scene-searching-4',
    arc_id: 'arc-searching',
    slug: 'the-scholars-path',
    is_start: false,
    is_end: false,
    light_world: false,
    title: "The Scholars' Journey",
    body: 'Far from the fields of Bethlehem, scholars lifted their eyes and saw a sign they could not ignore. Something in the heavens told them a true king had entered the world.\n\nSo they kept going. Through dust, distance, and delay, they followed the light because some truths are worth crossing countries to find.',
    audio_url: null,
    choices: [
      {
        id: 'choice-searching-4',
        scene_id: 'scene-searching-4',
        next_scene_id: 'scene-searching-4b',
        order: 0,
        label: 'Follow the star to where it finally rested',
      },
    ],
  },
  {
    id: 'scene-searching-4b',
    arc_id: 'arc-searching',
    slug: 'the-gifts-in-the-dust',
    is_start: false,
    is_end: false,
    light_world: false,
    title: 'The Gifts in the Dust',
    body: 'When they finally arrived, the scene before them did not match the grandeur of the journey. No marble hall. No court. No throne raised above the room.\n\nJust a child, ordinary dust, and a holiness that made kneeling feel like the most sensible thing in the world. Gold touched the floor. Learning bent into worship. Real kingship had been hiding where power never thinks to look.',
    audio_url: null,
    choices: [
      {
        id: 'choice-searching-4b',
        scene_id: 'scene-searching-4b',
        next_scene_id: 'scene-searching-5',
        order: 0,
        label: 'Keep following the question a true king leaves behind',
      },
    ],
  },
  {
    id: 'scene-searching-5',
    arc_id: 'arc-searching',
    slug: 'what-do-you-do-with-a-king',
    is_start: false,
    is_end: false,
    light_world: false,
    title: 'What Do You Do With a King?',
    body: 'A true king does not leave anyone neutral. Some people kneel because they have finally found someone worth trusting. Others pull back because real authority threatens every smaller throne they have built for themselves.\n\nThe question did not end in Bethlehem. It keeps finding every heart: what do you do when a true king actually arrives?',
    audio_url: null,
    choices: [
      {
        id: 'choice-searching-5',
        scene_id: 'scene-searching-5',
        next_scene_id: 'scene-searching-5b',
        order: 0,
        label: 'Keep following what this King came to do',
      },
    ],
  },
  {
    id: 'scene-searching-5b',
    arc_id: 'arc-searching',
    slug: 'the-table-he-kept',
    is_start: false,
    is_end: false,
    light_world: false,
    title: 'The Table He Kept',
    body: 'Before the cross ever came into view, he kept setting tables wide enough for the wrong people to sit down at. The ashamed. The compromised. The written-off. The ones polite religion had already placed outside the room.\n\nHis kingdom did not drift toward the polished and the certain. It moved, again and again, toward the lost as if they were exactly who he had come looking for.',
    audio_url: null,
    choices: [
      {
        id: 'choice-searching-5b',
        scene_id: 'scene-searching-5b',
        next_scene_id: 'scene-searching-5c',
        order: 0,
        label: 'Follow him toward the rescue he was making',
      },
    ],
  },
  {
    id: 'scene-searching-5c',
    arc_id: 'arc-searching',
    slug: 'the-city-that-did-not-know',
    is_start: false,
    is_end: false,
    light_world: false,
    title: 'The City That Did Not Know',
    body: 'He entered the city with the shape of a king and the heart of something far more dangerous to the world as it was. Branches lifted. Voices rose. Suspicion watched from the edges. Many looked straight at him and still did not know what they were seeing.\n\nThe rescue was already moving beneath the surface of the moment, even while the city failed to recognize the one who had come to save it.',
    audio_url: null,
    choices: [
      {
        id: 'choice-searching-5c',
        scene_id: 'scene-searching-5c',
        next_scene_id: 'scene-searching-6',
        order: 0,
        label: 'Stay with him through the rescue no one expected',
      },
    ],
  },
  {
    id: 'scene-searching-6',
    arc_id: 'arc-searching',
    slug: 'the-rescue',
    is_start: false,
    is_end: false,
    light_world: true,
    title: 'The Rescue',
    body: 'He healed what sickness had taken. He forgave what shame would not release. He welcomed people who had forgotten how to imagine belonging. And then he let violence do its worst to him.\n\nThe one who came to rescue the world was nailed to a cross by the very world he had come to rescue. Three days later, the tomb stood open and empty.',
    audio_url: null,
    choices: [
      {
        id: 'choice-searching-6',
        scene_id: 'scene-searching-6',
        next_scene_id: 'scene-searching-6b',
        order: 0,
        label: 'Stay with the morning that came after',
      },
    ],
  },
  {
    id: 'scene-searching-6b',
    arc_id: 'arc-searching',
    slug: 'the-dawn-after',
    is_start: false,
    is_end: false,
    light_world: true,
    title: 'The Dawn After',
    body: 'Then morning reached a place everyone had already given over to darkness. The women came carrying grief, spices, and the ordinary duties of sorrow. They left carrying news too bright to hold neatly.\n\nHope was no longer an idea people repeated to survive the night. It had stepped back into the world with a living body.',
    audio_url: null,
    choices: [
      {
        id: 'choice-searching-6b',
        scene_id: 'scene-searching-6b',
        next_scene_id: 'scene-searching-6c',
        order: 0,
        label: 'Keep walking until the news becomes invitation',
      },
    ],
  },
  {
    id: 'scene-searching-6c',
    arc_id: 'arc-searching',
    slug: 'the-opened-way',
    is_start: false,
    is_end: false,
    light_world: true,
    title: 'The Opened Way',
    body: 'If the tomb is empty, then death is not the final voice over this world after all. The rescue was never meant to be only a miracle people admired from a distance. It opened a road back to God for people who had wandered far, hidden long, or stopped believing they could come home.\n\nAt this point the story changes shape. It stops being only news to witness and becomes invitation to answer.',
    audio_url: null,
    choices: [
      {
        id: 'choice-searching-6c',
        scene_id: 'scene-searching-6c',
        next_scene_id: 'scene-searching-7',
        order: 0,
        label: 'Step closer to the invitation this living King gives',
      },
    ],
  },
  {
    id: 'scene-searching-7',
    arc_id: 'arc-searching',
    slug: 'the-invitation',
    is_start: false,
    is_end: true,
    light_world: true,
    title: 'The Invitation',
    body: 'This story is not sealed off in the past. The King still calls people from every place, every history, every kind of distance to come near.\n\nNot after they have made themselves better. Not once they understand everything. Now. As they are. The invitation is still open.',
    audio_url: null,
    choices: [],
  },
  {
    id: 'scene-curiosity-1',
    arc_id: 'arc-curiosity',
    slug: 'the-tree-at-noon',
    is_start: true,
    is_end: false,
    light_world: true,
    title: 'The Tree at Noon',
    body: 'Curiosity often looks like distance. Zacchaeus climbed a tree because he wanted to see without being seen.\n\nJesus did not let him remain a spectator for long.',
    audio_url: null,
    choices: [
      {
        id: 'choice-curiosity-1',
        scene_id: 'scene-curiosity-1',
        next_scene_id: 'scene-curiosity-2',
        order: 0,
        label: 'See what happens when Jesus looks up',
      },
    ],
  },
  {
    id: 'scene-curiosity-2',
    arc_id: 'arc-curiosity',
    slug: 'come-and-see-scene',
    is_start: false,
    is_end: false,
    light_world: true,
    title: 'Come and See',
    body: 'Jesus did not open with an argument. He opened with an invitation. "Come and see."\n\nThe curious were welcomed near enough to discover for themselves.',
    audio_url: null,
    choices: [
      {
        id: 'choice-curiosity-2',
        scene_id: 'scene-curiosity-2',
        next_scene_id: 'scene-curiosity-2b',
        order: 0,
        label: 'Stay long enough to hear him say your name',
      },
    ],
  },
  {
    id: 'scene-curiosity-2b',
    arc_id: 'arc-curiosity',
    slug: 'the-open-table',
    is_start: false,
    is_end: false,
    light_world: true,
    title: 'The Open Table',
    body: 'Jesus kept eating with people who did not fit the expected story. Curiosity became courage at tables like that, where nobody had to clean themselves up before sitting down.\n\nNearness came before understanding.',
    audio_url: null,
    choices: [
      {
        id: 'choice-curiosity-2b',
        scene_id: 'scene-curiosity-2b',
        next_scene_id: 'scene-curiosity-2c',
        order: 0,
        label: 'Stay close enough to realize he already knows you',
      },
    ],
  },
  {
    id: 'scene-curiosity-2c',
    arc_id: 'arc-curiosity',
    slug: 'the-second-look',
    is_start: false,
    is_end: false,
    light_world: true,
    title: 'The Second Look',
    body: 'Curiosity changes when you take a second look instead of moving on. Jesus had a way of making people linger because being near him felt more like discovery than pressure.\n\nHe was not afraid of slow attention. He seemed to welcome it.',
    audio_url: null,
    choices: [
      {
        id: 'choice-curiosity-2c',
        scene_id: 'scene-curiosity-2c',
        next_scene_id: 'scene-curiosity-3',
        order: 0,
        label: 'Keep looking until the invitation becomes personal',
      },
    ],
  },
  {
    id: 'scene-curiosity-3',
    arc_id: 'arc-curiosity',
    slug: 'the-name-he-knew',
    is_start: false,
    is_end: true,
    light_world: true,
    title: 'The Name He Knew',
    body: 'Before Nathanael had a category for Jesus, Jesus already knew him.\n\nSometimes curiosity becomes trust when you realize you are being seen more deeply than you expected.',
    audio_url: null,
    choices: [],
  },
  {
    id: 'scene-anger-1',
    arc_id: 'arc-anger',
    slug: 'the-waterline',
    is_start: true,
    is_end: false,
    light_world: false,
    title: 'The Waterline',
    body: 'Anger can feel like a storm with nowhere to go. The disciples knew that feeling on the lake. Wind in every direction. Water where the floor used to be.\n\nAnd Jesus, somehow, asleep in the middle of it.',
    audio_url: null,
    choices: [
      {
        id: 'choice-anger-1',
        scene_id: 'scene-anger-1',
        next_scene_id: 'scene-anger-2',
        order: 0,
        label: 'Stay in the boat long enough to hear what he says',
      },
    ],
  },
  {
    id: 'scene-anger-2',
    arc_id: 'arc-anger',
    slug: 'the-voice-in-the-storm',
    is_start: false,
    is_end: false,
    light_world: false,
    title: 'The Voice in the Storm',
    body: 'He stood and spoke into the noise. Not with panic. Not with more violence. With authority.\n\n"Peace. Be still." The chaos did not vanish because it was ignored. It yielded because someone greater named its limit.',
    audio_url: null,
    choices: [
      {
        id: 'choice-anger-2',
        scene_id: 'scene-anger-2',
        next_scene_id: 'scene-anger-2b',
        order: 0,
        label: 'See what remains when the waves finally go quiet',
      },
    ],
  },
  {
    id: 'scene-anger-2b',
    arc_id: 'arc-anger',
    slug: 'the-oars-in-the-night',
    is_start: false,
    is_end: false,
    light_world: false,
    title: 'The Oars in the Night',
    body: 'After the command, there was a strange pause. Hands still tight on the oars. Breath still catching up. Anger does not always leave in a single instant.\n\nSometimes peace begins as the first moment you realize the storm is no longer in charge.',
    audio_url: null,
    choices: [
      {
        id: 'choice-anger-2b',
        scene_id: 'scene-anger-2b',
        next_scene_id: 'scene-anger-2c',
        order: 0,
        label: 'Sit inside the deeper calm that follows',
      },
    ],
  },
  {
    id: 'scene-anger-2c',
    arc_id: 'arc-anger',
    slug: 'after-the-water',
    is_start: false,
    is_end: false,
    light_world: false,
    title: 'After the Water',
    body: 'The waves were down, but the disciples were still shaking. Sometimes anger leaves behind its own weather inside the body.\n\nJesus did not scold them for being late to peace. He stayed in the boat with them until the quiet felt real.',
    audio_url: null,
    choices: [
      {
        id: 'choice-anger-2c',
        scene_id: 'scene-anger-2c',
        next_scene_id: 'scene-anger-3',
        order: 0,
        label: 'Stay for the deeper calm that follows',
      },
    ],
  },
  {
    id: 'scene-anger-3',
    arc_id: 'arc-anger',
    slug: 'the-deeper-calm',
    is_start: false,
    is_end: true,
    light_world: true,
    title: 'The Deeper Calm',
    body: 'The lake became still, but so did something inside the boat.\n\nJesus did not shame their fear or their anger. He simply revealed that they were not alone inside it.',
    audio_url: null,
    choices: [],
  },
];

export const mockScenes: Record<string, SceneWithContent> = Object.fromEntries(
  mockScenesList.map((scene) => [scene.id, scene]),
);

const scenesByArcSlug = new Map<string, SceneWithContent[]>(
  mockArcs.map((arc) => [arc.slug, mockScenesList.filter((scene) => scene.arc_id === arc.id)]),
);

export function getMockPublishedArcs() {
  return mockArcs;
}

export function getMockArcBySlug(slug: string) {
  const arc = mockArcs.find((entry) => entry.slug === slug);
  if (!arc) {
    return null;
  }

  return {
    id: arc.id,
    slug: arc.slug,
    emotional_key: arc.emotional_key ?? null,
  };
}

export function getMockStartScene(arcSlug: string) {
  const scenes = scenesByArcSlug.get(arcSlug) ?? [];
  return scenes.find((scene) => scene.is_start) ?? null;
}

export function getMockScenesForArc(arcSlug: string) {
  return scenesByArcSlug.get(arcSlug) ?? [];
}

export function getMockSceneById(sceneId: string) {
  return mockScenes[sceneId] ?? null;
}

export function getMockCoordinatorMessages() {
  return [...mockCoordinatorMessages].sort((a, b) => b.created_at.localeCompare(a.created_at));
}

export const mockWitnessVideos: WitnessVideo[] = [
  {
    id: 'wv-grief',
    arc_id: 'arc-grief',
    emotional_key: 'grief',
    lang: 'en',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    poster_url: null,
    caption_url: null,
    speaker_name: 'Naomi',
  },
  {
    id: 'wv-doubt',
    arc_id: 'arc-doubt',
    emotional_key: 'doubt',
    lang: 'en',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    poster_url: null,
    caption_url: null,
    speaker_name: 'Daniel',
  },
  {
    id: 'wv-searching',
    arc_id: 'arc-searching',
    emotional_key: 'searching',
    lang: 'en',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    poster_url: null,
    caption_url: null,
    speaker_name: 'A witness',
  },
  {
    id: 'wv-curiosity',
    arc_id: 'arc-curiosity',
    emotional_key: 'curiosity',
    lang: 'en',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    poster_url: null,
    caption_url: null,
    speaker_name: 'Elias',
  },
  {
    id: 'wv-anger',
    arc_id: 'arc-anger',
    emotional_key: 'anger',
    lang: 'en',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    poster_url: null,
    caption_url: null,
    speaker_name: 'Mara',
  },
];
